#!/bin/sh
#
# Make a cluster with kind, get and deploy config metallb into it.
# Based on: https://mauilion.dev/posts/kind-metallb/
# Two arguments:

KINDCONFIG=$1
METALLBCONFIG=$2

# First create the cluster:
kind create cluster --config $KINDCONFIG

# Install metallb into the cluster:
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.4/manifests/namespace.yaml
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.9.4/manifests/metallb.yaml
# On first install only
kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)"

# And then we apply the metallb configuration:
kubectl apply -f $METALLBCONFIG

