apiVersion: v1
kind: Service
metadata:
  labels:
    app: echo
  name: echo
  namespace: default
spec:
  ports:
  - nodePort: 32353
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: echo
  sessionAffinity: None
  type: LoadBalancer
